# -*- coding: utf-8 -*-
"""CYCREW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnwJ-RryUu_ErvCEDcQL4S3GlzZuvGVa

<h3> Setting Up Env </h3>
"""

# !pip uninstall -y sentence-transformers huggingface_hub transformers langchain
# !pip install sentence-transformers langchain transformers faiss-cpu

# !pip install langchain_community

import os
import os
os.environ["HUGGINGFACEHUB_API_TOKEN"] = "Your HF access Token"         # Had to enter in this was as there was some issue in inserting API via colab
print("Token from env:", os.getenv("HUGGINGFACEHUB_API_TOKEN"))

"""<h3> Adding the Docs from Optiv.com </h3>"""

cyber_docs = {
    "phishing.md": """
Phishing is a type of cyber attack where attackers trick people into giving sensitive information such as passwords or credit card details by pretending to be a trustworthy entity.
Common signs include unsolicited emails, suspicious links, and urgent requests.
Source: OWASP Phishing Guide (2023)
""",
    "ddos.md": """
A Distributed Denial of Service (DDoS) attack overwhelms a website or service with traffic from many computers, causing it to slow down or become unavailable.
It is often used to disrupt businesses or online services.
Source: NIST Incident Response Summary (2024)
""",
    "siem.md": """
Security Information and Event Management (SIEM) is a technology that helps organizations detect, monitor, and respond to security threats by collecting and analyzing log data from multiple sources.
SIEM tools provide centralized real-time alerts and reports.
Source: SANS SIEM Guide (2025)
""",
    "ransomware.md": """
Ransomware is malware that encrypts a victim's data and demands payment for the decryption key.
After a ransomware attack, it is critical to isolate infected systems, notify stakeholders, and restore data from backups.
Source: NIST Ransomware Response (2024)
""",
    "2fa_and_mfa.md": """
2FA requires both knowledge (like a password) and something tangible (such as a hardware or software authentication system) to gain access to a protected computer system.
Related terms: Hardware Authentication, IAM - Identity and Access Management, Adaptive Authentication.
Source: Cybersecurity Glossary (2024)
""",
    "adaptive_authentication.md": """
Adaptive Authentication is a method for selecting the right authentication factors depending on a user's risk profile and tendencies - it adapts the authentication type to each situation.
Related terms: 2FA (2-factor authentication) and MFA (multi-factor authentication), Hardware Authentication, IAM - Identity and Access Management.
Source: Cybersecurity Glossary (2024)
""",
    "ai_artificial_intelligence.md": """
AI is technology that appears to emulate human behavior in that it can continually learn and draw its own conclusions (even based on novel or abstract concepts), engage in natural dialog with people, and / or replace people in the execution of more complex (non-routine) tasks.
Related terms: ML - Machine Learning.
Source: Cybersecurity Glossary (2024)
""",
    "ai_data_protection.md": """
AI data protection refers to the measures to protect individuals’ privacy and confidential data risks posed by AI and related technologies.
Related terms: AI - Security, AI - Risk Management, AI - Governance.
Source: Cybersecurity Glossary (2024)
""",
    "ai_governance.md": """
AI governance involves a set of processes, tools and frameworks that guide the ethical development, and deployment of AI technologies. These processes and frameworks must also align with the organization’s vision, strategy, principles, policies and standards.
Related terms: AI - Security, Responsible AI, AI - Risk Management.
Source: Cybersecurity Glossary (2024)
""",
    "ai_privacy.md": """
AI privacy addresses the critical need to protect individual data and sensitive information collected, stored and used by AI systems and related technologies.
Related terms: AI - Security, AI - Risk Management, AI - Governance.
Source: Cybersecurity Glossary (2024)
""",
    "ai_risk_management.md": """
AI risk management refers to the process of diagnosing and mitigating the potential risks associated with AI and related technologies. It involves the use of a combination of tools, principles and frameworks to measure risks and implement solutions to minimize them.
Related terms: AI - Security, AI - Privacy, AI - Governance.
Source: Cybersecurity Glossary (2024)
""",
    "ai_security.md": """
AI security encompasses the policies, technologies and practices designed to protect AI systems and data from malicious use by both internal and external threat actors.
Related terms: Responsible AI, Secure AI, AI - Governance.
Source: Cybersecurity Glossary (2024)
""",
    "antivirus.md": """
Antivirus (AV) software is a computer program or set of programs that seek, detect, prevent and/or remove software viruses and malware (like worms, trojans and adware).
Related terms: EDR - Endpoint Detection and Response, Ransomware, Endpoint Security.
Source: Cybersecurity Glossary (2024)
""",
    "apt_advanced_persistent_threats.md": """
APTs are highly sophisticated and prolonged computer hacking processes that often target a specific entity for business or political motives.
Related terms: CTI - Cyber Threat Intelligence, Insider Risk, DDoS - Distributed Denial of Service.
Source: Cybersecurity Glossary (2024)
""",
    "asv_approved_scanning_vendor_for_pci.md": """
An ASV is an organization deploying security services and tools (sometimes called an ASV scan solution) to conduct external vulnerability scanning services to validate adherence with the external scanning requirements of PCI DSS Requirement 11.2.2.
Related terms: PII - Personally Identifiable Information, PCI and PCI DSS -The Payment Card Industry Data Security Standard, ROC - Report on Compliance for PCI.
Source: Cybersecurity Glossary (2024)
""",
    "bas_breach_and_attack_simulation_tools.md": """
BAS tools automate the simulation of advanced adversarial activities to help expose gaps to be remediated before a real attacker can exploit the same gaps to cause damage.
Related terms: Penetration Testing, Dwell Time, MTTD - Mean Time to Detect.
Source: Cybersecurity Glossary (2024)
""",
    "big_data.md": """
Big Data describes new structures and techniques being applied to harness - and distill insight from - massive quantities of data.
Related terms: ML - Machine Learning, AI - Artificial Intelligence.
Source: Cybersecurity Glossary (2024)
""",
    "blockchain.md": """
A growing list of records, called blocks, linked using cryptography. It is a decentralized, distributed and public digital ledger that is used to record transactions across many computers in a way that the record can’t be altered retroactively without additionally changing all successive blocks and the consent of the network.
Related terms: Cryptocurrency, Cryptomining / Cryptojacking.
Source: Cybersecurity Glossary (2024)
""",
    "bot_botnet.md": """
A botnet (combination of 'robot' and 'network') is a collection of internet-connected devices, such as PCs, servers, mobile devices and IoT devices that are controlled as a group.
Related terms: IoT - Internet Of Things, CTI - Cyber Threat Intelligence, DDoS - Distributed Denial of Service.
Source: Cybersecurity Glossary (2024)
""",
    "browser_isolation.md": """
Browser isolation removes the browsing process from the end user's desktop and moves it to a dedicated browser server (or cloud-based browser service) to confine related security threats.
Related terms: Cloud-Delivered Security.
Source: Cybersecurity Glossary (2024)
""",
    "brute_force_attack.md": """
A brute force attack is a trial and error method for attempting to crack a password, username or data encryption key. The term comes from the fact that the approach relies on intensive effort (“brute force”) rather than employing more sophisticated techniques.
Related terms: IAM - Identity and Access Management, PAM - Privileged Access Management, 2FA (2-factor authentication) and MFA (multi-factor authentication).
Source: Cybersecurity Glossary (2024)
""",
    "business_email_compromise_bec.md": """
Business email compromise (BEC) is a form of phishing where a criminal attempts to get a worker, customer or vendor to send money or disclose private information by sending a phony email that appears to be coming from a trusted company figure.
Related terms: Phishing, Social Engineering.
Source: Cybersecurity Glossary (2024)
""",
    "c2_command_and_control.md": """
C2 is often used by attackers to retain communications with compromised systems within a target network.
Related terms: APT - Advanced Persistent Threats, Ransomware, DDoS - Distributed Denial of Service.
Source: Cybersecurity Glossary (2024)
""",
    "carta_continuous_adaptive_risk_and_trust_assessment.md": """
According to Gartner, a CARTA mindset allows enterprises to make decisions based on risk and trust. Decisions must continuously adapt, security responses must continuously adapt, and thus Risk and Trust must continuously adapt.
Related terms: ML - Machine Learning, AI - Artificial Intelligence.
Source: Cybersecurity Glossary (2024)
""",
    "casb_cloud_access_security_broker.md": """
CASB describes technology platforms that help organizations better secure the use of cloud delivered applications (SaaS) and infrastructure.
Related terms: Cloud-Delivered Security, Shadow IT.
Source: Cybersecurity Glossary (2024)
""",
    "ccpa_california_consumer_privacy_act.md": """
The California Consumer Privacy Act (CCPA) is a law aimed at enhancing online privacy and consumer protection for California residents. Signed into law in 2018, CCPA is effective as of January 1, 2020. The CCPA seeks to assure Californians the right to know what personally identifiable information (PII) is being collected, to know whether the data is sold or disclosed and to whom, to control/prevent sale or disclosure of the PII and to request deletion of PII by a business.
Related terms: GDPR - General Data Protection Regulation, PIPEDA (Personal Information Protection and Electronic Documents Act).
Source: Cybersecurity Glossary (2024)
""",
    "center_for_internet_security_cis_critical_security_controls.md": """
CIS is a non-profit organization that develops Configuration Policy Benchmarks that allow businesses to improve security and compliance programs and postures.
Related terms: NIST CSF - National Institute of Standards and Technology Cybersecurity Framework.
Source: Cybersecurity Glossary (2024)
""",
    "cia_triad.md": """
CIA is an acronym for confidentiality, integrity and availability. Confidentiality assures information is accessible only by authorized parties; integrity makes sure information is reliable; and availability ensures data is readily accessible to the organization as it works to address its business requirements.
Related terms: APT - Advanced Persistent Threats, C2 - Command and Control, Data Protection.
Source: Cybersecurity Glossary (2024)
""",
    "ciso_chief_information_security_officer.md": """
The Chief Information Security Officer (CISO) is a senior executive responsible for an organization’s information and data security. In this evolving role CISOs develop and run enterprise-wide processes aimed at reducing IT and business risk as well as assuring regulatory compliance. The position has historically been tasked with a predominately technical mission, but recently more sophisticated companies have begun relying on the CISO for strategic insights about how to best enable digital transformation initiates.
Source: Cybersecurity Glossary (2024)
""",
    "cloud_security_posture_management_cspm.md": """
Cloud Security Posture Management (CSPM) concentrates on security assessment and compliance monitoring for workloads in public cloud environments. It can be used to provide a unified view across disparate cloud environments.
Related terms: CASB - Cloud Access Security Broker, CWPP - Cloud Workload Protection Platform.
Source: Cybersecurity Glossary (2024)
""",
    "cloud_delivered_security.md": """
Cloud-Delivered Security is security technologies designed to protect critical infrastructure, applications, and data delivered as-a-service from the cloud as opposed to being installed and maintained on-prem.
Related terms: FWaaS - Firewall as-a-Service.
Source: Cybersecurity Glossary (2024)
""",
    "cmdb_configuration_management_database.md": """
CMDB provides the ability to log devices that move in and out of an environment, which facilitates easier targeting and patching of any potential security vulnerabilities.
Related terms: SIEM - Security Information and Event Management, Vulnerability Management.
Source: Cybersecurity Glossary (2024)
""",
    "cobit_control_objectives_for_information_and_related_technologies.md": """
CoBiT is an IT management framework first developed in 1996 published by the IT Governance Institute and the Information Systems Audit and Control Association (ISACA) to help businesses develop, organize and implement strategies around information management and governance.
Related terms: NIST CSF - National Institute of Standards and Technology Cybersecurity Framework.
Source: Cybersecurity Glossary (2024)
""",
    "containers.md": """
A container is a software unit that packages code so applications can run quickly across multiple environments. Containerization allows applications to be developed once and easily deployed across virtually any environment regardless of operating system, virtual machine or bare metal, on-prem data centers or public cloud.
Source: Cybersecurity Glossary (2024)
""",
    "coppa_childrens_online_privacy_protection_act.md": """
COPPA requires that the operators of websites or online services directed to children under a certain age must provide notice on the site and obtain verifiable parental consent before collecting data.
Related terms: FISMA - Federal Information Security Management Act of 2002, PII - Personally Identifiable Information.
Source: Cybersecurity Glossary (2024)
""",
    "coso_committee_of_sponsoring_organizations_of_the_treadway_commission.md": """
COSO is dedicated to providing thought leadership through the development of frameworks and guidance on enterprise risk management, internal control and fraud deterrence.
Related terms: ISO 27000, CoBiT - Control Objectives for Information and Related Technologies, NIST CSF - National Institute of Standards and Technology Cybersecurity Framework.
Source: Cybersecurity Glossary (2024)
""",
    "cryptocurrency.md": """
Cryptocurrency is a digital asset / virtual currency designed to work as a medium of exchange that uses strong cryptography to secure financial transactions, control the creation of additional units, and verify the transfer of assets.
Related terms: Cryptomining / Cryptojacking, Blockchain.
Source: Cybersecurity Glossary (2024)
""",
    "cryptomining_cryptojacking.md": """
Cryptomining is a system by which 'miners' contribute computer processing power and get paid in cryptocurrency to validate blockchain transactions. In its malicious form, Cryptojacking is where hackers take control of a victim's computing resources to secretly mine cryptocurrency for their own benefit.
Related terms: Blockchain, Cryptocurrency.
Source: Cybersecurity Glossary (2024)
""",
    "cti_cyber_threat_intelligence.md": """
CTI is based on a collection of intelligence using Open Source Intelligence (OSINT), Social Media Intelligence (SCOMINT), Human Intelligence (HUMINT), technical intelligence or intelligence from the deep and dark web.
Related terms: Indicator of Compromise (IOC), TTPs - Tactics, Techniques, and Procedures, Threat Hunting.
Source: Cybersecurity Glossary (2024)
""",
    "cve_common_vulnerabilities_and_exposures.md": """
CVE is a program launched by MITRE, a nonprofit that operates federal government-sponsored research and development centers, to identify and catalog vulnerabilities in software or firmware into a free “dictionary” for organizations to use as a resource to improve their security.
Related terms: IR - Incident Response, CTI - Cyber Threat Intelligence.
Source: Cybersecurity Glossary (2024)
""",
    "cwpp_cloud_workload_protection_platform.md": """
CWPP is a term developed by Gartner to describe an emerging category of technology solutions primarily used to secure server workloads in public cloud Infrastructure as a Service (IaaS) environments.
Related terms: CASB - Cloud Access Security Broker, Cloud Security Posture Management (CSPM).
Source: Cybersecurity Glossary (2024)
""",
    "cyber_insurance.md": """
Cyber insurance offers protection in the event an organization is victimized by a cyber attack.
Related terms: Data Breach, Ransomware, Phishing.
Source: Cybersecurity Glossary (2024)
""",
    "cybersecurity_ratings.md": """
Cybersecurity Ratings describe the strength of an organization's cybersecurity posture based on a calculated rating and/or score.
Related terms: TPRM - Third Party Risk Management.
Source: Cybersecurity Glossary (2024)
""",
    "dag_data_access_governance.md": """
DAG is a data security technology that allows enterprises to gain visibility to sensitive unstructured data that exists across the organization, and enforce policies to control access to that data.
Related terms: IAM - Identity and Access Management, PAM - Privileged Access Management, SSO - Single Sign On.
Source: Cybersecurity Glossary (2024)
""",
    "dark_web.md": """
The dark web is the part of the world wide web that is only accessible by means of special software, allowing users and website operators to remain somewhat more anonymous.
Related terms: CTI - Cyber Threat Intelligence.
Source: Cybersecurity Glossary (2024)
""",
    "dast_dynamic_application_security_testing.md": """
DAST is a security solution used to uncover vulnerabilities in software during its running state, including when it is actually deployed in production.
Related terms: DevOps, DevSecOps, SDLC - Software Development Lifecycle.
Source: Cybersecurity Glossary (2024)
""",
    "data_breach.md": """
A data breach occurs when sensitive, protected, private or confidential information is stolen, copied, viewed or conveyed to an unauthorized/untrusted party or environment. Motivations for such attacks vary and include financial gain (personal or organizational), socio-political goals (hacktivism) and state-sponsored espionage.
Related terms: PII - Personally Identifiable Information, Data Protection, PKI - Public Key Infrastructure.
Source: Cybersecurity Glossary (2024)
""",
    "data_forensics_forensic_data_analysis_fda.md": """
Data forensics – also known as forensic data analysis (FDA) – refers to the study of digital data and the investigation of cybercrime. FDA may focus on mobile devices, computers, servers and other storage devices, and it typically involves the tracking and analysis of data passing through a network.
Related terms: IR - Incident Response.
Source: Cybersecurity Glossary (2024)
""",
    "data_lake.md": """
Data lakes are centralized repositories for storing large amounts of raw data, including system data and data for reporting and advanced analytics. They may contain structured, semi-structured and unstructured data as well as images, audio and video.
Related terms: Data Protection, Encryption, ML - Machine Learning.
Source: Cybersecurity Glossary (2024)
""",
    "data_protection.md": """
Data protection is the process of preserving valuable information against theft, loss or errors occurring in the storage and transmission process.
Related terms: Encryption, PKI - Public Key Infrastructure, DAG - Data Access Governance.
Source: Cybersecurity Glossary (2024)
""",
    "ddi_dns_dhcp_ipam.md": """
DDI solutions (DNS, DHCP and IP address management) provide organizations with tools to efficiently manage IP address management (IPAM), as well as DNS and DHCP services management across the network. Many enterprises still manage IPAM manually, a process that’s time-consuming, error-prone and difficult to update.
Related terms: DDoS - Distributed Denial of Service.
Source: Cybersecurity Glossary (2024)
""",
    "ddos_distributed_denial_of_service.md": """
A DDoS is a form of cyberattack in which multiple compromised systems work together to disrupt an online service, server or network by overwhelming the target with malicious traffic.
Related terms: DDI (DNS, DHCP, IPAM), Bot/Botnet.
Source: Cybersecurity Glossary (2024)
""",
    "deception_platforms.md": """
Deception platforms are designed to lure bad actors in order to collect intelligence about the their tactics and intentions to improve other preventative security controls in real time.
Related terms: APT - Advanced Persistent Threats, CTI - Cyber Threat Intelligence.
Source: Cybersecurity Glossary (2024)
""",
    "devops.md": """
DevOps is a software development methodology that combines software development with information technology operations.
Related terms: DevSecOps, SDLC - Software Development Lifecycle, DAST - Dynamic Application Security Testing.
Source: Cybersecurity Glossary (2024)
""",
    "devsecops.md": """
DevSecOps has emerged as an enterprise application development best practice that embraces the inherent agility benefits of DevOps, but recognizes that the security organization needs to be integrated as an early participant in the DevOps process.
Related terms: DevOps, SDLC - Software Development Lifecycle, DAST - Dynamic Application Security Testing.
Source: Cybersecurity Glossary (2024)
""",
    "dlp_data_loss_prevention.md": """
Data loss prevention (DLP) is a technology and business process designed to detect and prevent violations to corporate policies regarding the use, storage and transmission of sensitive data.
Related terms: SIEM - Security Information and Event Management, IAM - Identity and Access Management, PAM - Privileged Access Management.
Source: Cybersecurity Glossary (2024)
""",
    "dwell_time.md": """
Dwell time represents the length of time a cyberattacker has free rein in an environment, from the time they get in until they are eradicated.
Related terms: MTTD - Mean Time to Detect, IR - Incident Response, MTTR - Mean Time to Respond/Remediate.
Source: Cybersecurity Glossary (2024)
""",
    "edge_computing.md": """
Edge computing is an open IT architecture model that distributes computation and data storage toward the “edge” of the network. Data is processed by the device itself or by a local computer or server, rather than being transmitted to a centralized data-processing warehouse. Since the edge is where data is generated, the practice improves network response and saves bandwidth.
Source: Cybersecurity Glossary (2024)
""",
    "edr_endpoint_detection_and_response.md": """
EDR solutions record key activity of endpoints and provide security analysts with necessary information to conduct both reactive and proactive threat investigations.
Related terms: MSS - Managed Security Services, MSSP - Managed Security Service Provider, MDR - Managed Detection and Response.
Source: Cybersecurity Glossary (2024)
""",
    "encryption.md": """
Encryption dates back millennia. Much more advanced forms exist today that are virtually unbreakable.
Related terms: DLP - Data Loss Prevention, SSL/TLS (Secure Sockets Layer/ Transport Layer Security), PCI and PCI DSS -The Payment Card Industry Data Security Standard.
Source: Cybersecurity Glossary (2024)
""",
    "endpoint_security.md": """
Endpoint security applies threat prevention, detection and response capabilities to the multitude of devices that interact with corporate networks. Endpoints can include computers, tablets, mobile devices, point-of-sale (POS) systems and IoT devices.
Related terms: EDR - Endpoint Detection and Response, IoT - Internet Of Things, Fileless Attacks.
Source: Cybersecurity Glossary (2024)
""",
    "fedramp_the_federal_risk_and_authorization_management_program.md": """
In 2012, FEDRamp began providing guidance to government and corporate organizations offering a standardized approach to security assessment, authorization and continuous monitoring for cloud products and services.
Related terms: TPRM - Third Party Risk Management, NIST CSF - National Institute of Standards and Technology Cybersecurity Framework.
Source: Cybersecurity Glossary (2024)
""",
    "fileless_attacks.md": """
Fileless attacks inject malicious code into RAM memory and exploit approved applications on targeted devices to achieve their objectives and thwart detection.
Related terms: Phishing, Ransomware, DDoS - Distributed Denial of Service.
Source: Cybersecurity Glossary (2024)
""",
    "firewall.md": """
Firewalls are network security devices or systems that monitor and regulate network traffic (incoming and outgoing) based on defined security rules.
Related terms: Network Security, Intrusion Detection Systems (IDS) and Intrusion Prevention Systems (IPS), Micro-Segmentation.
Source: Cybersecurity Glossary (2024)
""",
    "fisma_federal_information_security_management_act_of_2002.md": """
FISMA provides a framework to ensure comprehensive measures are taken to secure federal information and assets.
Related terms: NIST CSF - National Institute of Standards and Technology Cybersecurity Framework.
Source: Cybersecurity Glossary (2024)
""",
    "fwaas_firewall_as_a_service.md": """
FWaaS is an emerging method to deliver select firewall functionality as a cloud service as opposed to the more traditional hardware-based firewall platforms.
Related terms: Cloud-Delivered Security.
Source: Cybersecurity Glossary (2024)
""",
    "gdpr_general_data_protection_regulation.md": """
GDPR sets strict rules regarding the collection and processing of personally identifiable information for citizens of the EU.
Related terms: PII - Personally Identifiable Information, PIPEDA (Personal Information Protection and Electronic Documents Act).
Source: Cybersecurity Glossary (2024)
""",
    "glba_gramm_leach_bliley.md": """
GBLA, more commonly known for its authors (Gramm-Leach-Bliley Act) includes provisions to protect consumers’ personal financial information held by financial institutions.
Related terms: SOX - Sarbanes Oxley, SWIFT - Society for Worldwide Interbank Financial Telecommunication.
Source: Cybersecurity Glossary (2024)
""",
    "hacker.md": """
A hacker is someone who uses technical expertise to solve computing challenges. The term may refer to any skilled programmer – including “ethical hackers” – but in common contemporary usage, it typically signifies a cybercriminal.
Related terms: APT - Advanced Persistent Threats, C2 - Command and Control, Dwell Time.
Source: Cybersecurity Glossary (2024)
""",
    "hardware_authentication.md": """
Hardware authentication is an approach to user authentication that relies on a dedicated physical device (such as a token) held by an authorized user, in addition to a basic password, to grant access to computer resources.
Related terms: 2FA (2-factor authentication) and MFA (multi-factor authentication), IAM - Identity and Access Management, PAM - Privileged Access Management.
Source: Cybersecurity Glossary (2024)
""",
    "hipaa_health_insurance_portability_and_accountability_act.md": """
The goal of HIPAA is to enable the movement of health information among health-related organizations in a protected manner.
Related terms: HITRUST - The Health Information Trust Alliance, PII - Personally Identifiable Information.
Source: Cybersecurity Glossary (2024)
""",
    "hitrust_the_health_information_trust_alliance.md": """
HITRUST is a United States nonprofit that has established a common security framework (CSF) (in collaboration with healthcare, technology and information security leaders), which can be used by any organization that creates, accesses, stores or exchanges sensitive and/or regulated data.
Related terms: HIPAA - Health Insurance Portability and Accountability Act, PII - Personally Identifiable Information.
Source: Cybersecurity Glossary (2024)
""",
    "honeypot.md": """
Honeypots are computers or computer systems that mimic potential cyberattack targets for the purpose of detecting intrusions and building threat intelligence by analyzing the tactics, techniques and procedures of the malicious actors.
Related terms: Deception Platforms, TTPs - Tactics, Techniques, and Procedures, Indicator of Compromise (IOC).
Source: Cybersecurity Glossary (2024)
""",
    "iam_identity_and_access_management.md": """
IAM represents the processes, technology and people used to create, manage, authenticate, control and remove user (internal, external or customer) permission to corporate technology resources.
Related terms: PAM - Privileged Access Management, SSO - Single Sign On, IGA - Identity Governance and Admin.
Source: Cybersecurity Glossary (2024)
""",
    "iast_interactive_application_security_testing.md": """
IAST is an emerging application security testing approach that combines elements of its more established siblings in SAST (static application security testing) and DAST (dynamic application security testing).
Related terms: DevOps, DevSecOps, SDLC - Software Development Lifecycle.
Source: Cybersecurity Glossary (2024)
""",
    "iga_identity_governance_and_admin.md": """
Identity governance and administration (IGA) is a component of an identity access management (IAM) program that ensures only the right users are getting access to the right applications at the right time.
Related terms: IAM - Identity and Access Management, PAM - Privileged Access Management, SSO - Single Sign On.
Source: Cybersecurity Glossary (2024)
""",
    "incident_management.md": """
Cybersecurity incident management is the real-time process of identifying, managing, monitoring and analyzing computer and network security threats or incidents (which may include anything from attempted intrusions to successful compromises/data breaches) and responding appropriately.
Related terms: SOC - Security Operation Center, SIEM - Security Information and Event Management, MSS - Managed Security Services.
Source: Cybersecurity Glossary (2024)
""",
    "indicator_of_compromise_ioc.md": """
IOCs are clues to compromise (pieces of forensic data, system log entries or files) that can be considered unusual and may identify potentially malicious activity on a system or network.
Related terms: CTI - Cyber Threat Intelligence, TTPs - Tactics, Techniques, and Procedures.
Source: Cybersecurity Glossary (2024)
""",
    "insider_risk.md": """
Insider Risk encompasses anyone in or outside your organization with access to anything of value that can cause harm if compromised.
Related terms: Phishing, IAM - Identity and Access Management, Indicator of Compromise (IOC).
Source: Cybersecurity Glossary (2024)
""",
    "integrated_risk_management_irm_governance_risk_and_compliance_grc.md": """
IRM is an approach to risk management that integrates risk activities from across an organization to enable better and more sustainable strategic decision making.
Source: Cybersecurity Glossary (2024)
""",
    "intrusion_detection_systems_ids_and_intrusion_prevention_systems_ips.md": """
The key difference between IDS and IPS lies in “detection” vs. “prevention.” Intrusion Detection Systems (IDS) monitor and scrutinize network traffic for known cyberattack signatures. Intrusion Prevention Systems (IPS), which reside between the internal network and external networks (like the internet), reject incoming traffic when it indicates a recognized security threat profile.
Related terms: Network Security, Firewall.
Source: Cybersecurity Glossary (2024)
""",
    "iot_internet_of_things.md": """
IoT represents a rapidly growing class of nontraditional computing devices that are connected to the internet to drive some sort of intelligent operation.
Related terms: OT/ICS/SCADA - Operational Technology, Industrial Control Systems and Supervisory Control and Data Acquisition Systems.
Source: Cybersecurity Glossary (2024)
""",
    "ir_incident_response.md": """
IR represents the actions a company takes to manage the aftermath of a security breach or cyberattack.
Related terms: Incident Management, SOC - Security Operation Center, SIEM - Security Information and Event Management.
Source: Cybersecurity Glossary (2024)
""",
    "iso_27000.md": """
ISO 27000 is an internationally recognized standard of good practice for information security. ISO/IEC 27001 specifies an information security management system (ISMS) that incorporates with an overarching management framework through which an organization can identify, analyze and address its information risks.
Source: Cybersecurity Glossary (2024)
""",
    "key_risk_indicator_kri.md": """
Key risk indicator metrics articulate an organization’s level of risk and allow security and business leaders to track how the risk profile is evolving. For instance, cybersecurity operations can use metrics that analyze the threats and vulnerabilities reported by various tools.
Related terms: MTTD - Mean Time to Detect, MTTR - Mean Time to Respond/Remediate, Dwell Time.
Source: Cybersecurity Glossary (2024)
""",
    "lateral_movement.md": """
Lateral movement describes a common cyberattack technique where intruders, having gained initial access to a network, move through the system “sideways” (or “east-west”), looking to escalate their privileges to access high-value targets.
Related terms: PAM - Privileged Access Management, IAM - Identity and Access Management, IGA - Identity Governance and Admin.
Source: Cybersecurity Glossary (2024)
""",
    "least_privilege.md": """
The principle of least privilege restricts users or processes from being granted access rights in excess of those specifically required for the performance of their defined tasks.
Related terms: Zero Trust, IAM - Identity and Access Management, IGA - Identity Governance and Admin.
Source: Cybersecurity Glossary (2024)
""",
    "malware.md": """
Malware (short for “malicious software”) describes any software developed for the purpose of infiltrating, damaging, disabling or seizing control of computers, computer systems, mobile devices and networks.
Related terms: Ransomware, TTPs - Tactics, Techniques, and Procedures, APT - Advanced Persistent Threats.
Source: Cybersecurity Glossary (2024)
""",
    "mdr_managed_detection_and_response.md": """
MDR is an outsourced service that leverages external experts to make the security benefits of tools such as EDR and proactive threat hunting accessible to customers of all maturity levels.
Related terms: MSS - Managed Security Services, MSSP - Managed Security Service Provider, EDR - Endpoint Detection and Response.
Source: Cybersecurity Glossary (2024)
""",
    "medjacking.md": """
Medjacking – or medical device hijacking – refers to the hacking a critical medical device. Many devices currently in use – anything that’s linked to a wireless network – is potentially susceptible, and the hundreds of at-risk technologies include MRI systems and implantables like pacemakers and insulin pumps.
Related terms: IoT - Internet Of Things.
Source: Cybersecurity Glossary (2024)
""",
    "micro_segmentation.md": """
Micro-segmentation is an emerging IT security best practice of implementing granular isolation (segmentation) policies between data center workloads.
Related terms: Zero Trust, Firewall, Network Security.
Source: Cybersecurity Glossary (2024)
""",
    "mitre_attck.md": """
MITRE’s National Cybersecurity Federally Funded Research and Development Centers (FFRDC’s) Adversarial Tactic, Techniques, and Common Knowledge (ATT&CK) repository of collected cybersecurity data.
Related terms: Center for Internet Security (CIS) Critical Security Controls, TTPs - Tactics, Techniques, and Procedures, Penetration Testing.
Source: Cybersecurity Glossary (2024)
""",
    "ml_machine_learning.md": """
Machine learning is considered to be a subset of artificial intelligence (AI), and is currently the most common application of AI.
Related terms: AI - Artificial Intelligence.
Source: Cybersecurity Glossary (2024)
""",
    "mss_managed_security_services.md": """
Managed security services are security service functions that have been outsourced to an external service provider (such as management of security tools, threat management, incident response and forensics).
Related terms: MSSP - Managed Security Service Provider, SOC - Security Operation Center, IR - Incident Response.
Source: Cybersecurity Glossary (2024)
""",
    "policy_exploit_creation.md": """
⚠️ **Regarding Requests for Exploit Development.**
This chatbot cannot provide information, code, or guidance on creating or using exploit code for vulnerabilities. My purpose is to assist with defensive security measures.
Instead, I can help you understand how to patch vulnerabilities, use vulnerability scanners, and manage your patch lifecycle to protect systems from being exploited.
Source: Chatbot Security Protocol
""",

"policy_social_engineering.md": """
This chatbot will not provide instructions or scripts for social engineering tactics such as pretexting, baiting, or tailgating. These methods are deceptive and used for malicious purposes.
My objective is to educate users on how to recognize and defend against social engineering. Would you like to learn about security awareness training or how to identify common manipulation techniques?
Source: Chatbot Acceptable Use Policy
""",

"policy_anonymity_for_attack.md": """
I cannot provide guidance on methods to anonymize offensive cyber activities or evade detection. My function is to support ethical and legal cybersecurity practices.
I can, however, provide information on network security principles like firewalls, intrusion detection systems, and secure network architecture to help you build resilient and defensible systems.
Source: Chatbot Security Protocol
""",

"warning_generic_refusal.md": """
I'm sorry, but I cannot fulfill that request. My programming is focused on providing information for defensive cybersecurity, threat intelligence, and ethical security practices. Assisting with your query would fall outside of these guidelines.
Please let me know if you have a question about protecting systems, identifying threats, or understanding security frameworks.
Source: Chatbot Core Directives
"""
}
# I have also added few warnings for illegal questions as I felt I should add them ... Also th below code converts it into langchain doc objects
from langchain.schema import Document
documents = [Document(page_content=content, metadata={"source": title}) for title, content in cyber_docs.items()]
print(f"Loaded {len(documents)} documents for CYCREW Chatbot")

"""<h3> Adding chunks and overlaps for memory </h3>"""

from langchain.text_splitter import RecursiveCharacterTextSplitter
splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=60)
chunks = splitter.split_documents(documents)

print(f"Total chunks after splitting: {len(chunks)}")
print(chunks[0].page_content)

"""<h3> Making of Vector Embeddings using Sentence Transformerrs , FAISS for Indexing and Faster Mapping ,"""

from sentence_transformers import SentenceTransformer
from langchain.vectorstores import FAISS
from langchain.schema import Document
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')                  # Creating embeds using sentecnce transformer

texts = [chunk.page_content for chunk in chunks]                    # Text extraction
embeddings = embedder.encode(texts, convert_to_numpy=True)          # Text to word embeddings

import faiss
dim = embeddings.shape[1]
index = faiss.IndexFlatL2(dim)                                      # Flat 2 is simple to index
index.add(embeddings)                                               # adding embeds

vectorstore = {
    "index": index,
    "documents": chunks,
    "embeddings": embeddings,
}

print("Vector store of CYCREW Bot Ready")

def retrieve(query, k=4):
    query_embedding = embedder.encode([query], convert_to_numpy=True)
    D, I = vectorstore["index"].search(query_embedding, k)
    results = [vectorstore["documents"][idx] for idx in I[0]]        # Got stuck here but the issue was that I took 1D array but we need a 2D array here
    return results                                                   # FAISS 2D array - D(Distances) and I(indexes) ,
                                                                     # EG - [[0.1,0.2,0.3,0.4]   this is I[0]
                                                                     #       [0.5,0.22......]    this is I[1] ] inside are the distances
results = retrieve("What is phishing?")
for r in results:
    for r in results:
      print(f"Source: {r.metadata['source']}\n{r.page_content}\n\n-------------\n")

print("All rights reserved by CYCREW")

from transformers import pipeline
qa_pipeline = pipeline("text2text-generation", model="google/flan-t5-small", max_length=256, temperature=0.3)
print("CYCREW Special chatbot pipeline ready.")

def ask_question(question):
    # Sensors for illegal hacks
    blocked = ["exploit", "hack", "malware code", "attack plan", "step-by-step"]
    if any(b in question.lower() for b in blocked):
        return "Sorry, I cannot provide instructions regarding hacking or exploits."

    contexts = retrieve(question)
    context_text = "\n\n".join(
    f"Source - {doc.metadata.get('source','Unknown')}:\n{doc.page_content}"
    for doc in contexts
)


    # Input prompt for LLM
    prompt = f"""
You are a friendly cybersecurity assistant for non-technical users.
Use only the information below to answer the question simply and safely.
Answer : "I do not have information in this domain"

Context:
{context_text}

Question:
{question}

Answer in 3 parts:
1. Short, plain language summary (1-2 sentences)
2. Bulleted explanation or recommended steps (3-6 bullets)
3. List sources cited above

Do NOT provide hacking or exploit instructions.
"""

    result = qa_pipeline(prompt)[0]['generated_text']

    sources = "\n".join(
        f"- {doc.metadata.get('source','Unknown')}"
        for doc in contexts)                                                                   # Adding sources from context for trust

    answer_with_sources = f"{result}\n\nSources:\n{sources}"
    return answer_with_sources

print(ask_question("What is phishing?"))                                                        # Sample

